In [1]:
import numpy as np
import pandas as pd

Multiple series together are called as Dataframes

In [2]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

In [3]:
df = pd.DataFrame(data) # we can create dataframes just by passing data to the Dataframe attribute

In [4]:
df # df is usally used to print the complete dataframe

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
df2 = pd.DataFrame(df)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [23]:
# we can also set columns individually
columns = ["Name","Age","City","Salary"]
df3 = pd.DataFrame(data, columns=columns)
df3

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
# selecting a column, similarly we can select a row as well 
df3[["Name"]]

         Name
Name     John
Age      Anna
City    Peter
Salary  Linda

In [24]:
# we can create new column as well 
df3["Designation"] = ["Doc","engg","consultant","arch"]
df3 # like this we can add new columns as well

    Name  Age      City  Salary Designation
0   John   28  New York   65000         Doc
1   Anna   34     Paris   70000        engg
2  Peter   29    Berlin   62000  consultant
3  Linda   42    London   85000        arch

In [25]:
# deleting a column 
df3.drop('Designation', axis=1, inplace=True, errors='ignore')
# if we dont do the inplace the changes wont propagate to the actual dataframe hence we set inplace = True

In [ ]:
df3.loc[0]  # the loc is used to select the rows in the table we cant directly access them we must use loc

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [ ]:
df3.loc[[0,1]][["City","Salary"]] # so in here we selected a subset first we selected the the rows 0,1 and then we selected the city and salary also

       City  Salary
0  New York   65000
1     Paris   70000

In [28]:
df3.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

Conditional selection

In [ ]:
# selecting those whose age > 30
df3[df3["Age"]>30] # this gives us only those whose age was > 30

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [30]:
# selecting age > 30 and city paris
df3[(df3["Age"]>30) & (df3["City"]== 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000