In [1]:
import numpy as np
import pandas as pd

In [2]:
import pandas as pd

df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [3]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [4]:
df2

   score
2     85
3     90
4     75

In [ ]:
df1.join(df2) # df1 is the outer column and df2 is the inner one

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [ ]:
df2.join(df1) # now the score comes first

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN