In [1]:
import numpy as np
import pandas as pd

In [6]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [2, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)
print(df)

     A  B    C    D
0  1.0  2  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [7]:
df.isna() # wherever there is null there it shows false and true otherwise

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [8]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [9]:
df.isna().any() # this tells us if the all the columns are filled if all the columns are not filled then it returns false

A     True
B    False
C     True
D     True
dtype: bool

In [ ]:
df.dropna() # the dropna is usually used to drop the data which is null and it works row wise as in here only 0th row had no NULL values hence only it survived

     A  B    C    D
0  1.0  2  1.0  1.0

In [11]:
df.dropna(thresh=4) # tbis means only drop those rows which have minimum of 4 Non NULL values in themv

     A  B    C    D
0  1.0  2  1.0  1.0

In [12]:
df.fillna(12) # fills the value NULL values with 12

      A  B     C     D
0   1.0  2   1.0   1.0
1   2.0  2   2.0  12.0
2  12.0  3   3.0  12.0
3   4.0  4  12.0  12.0
4   5.0  5  12.0   5.0

In [ ]:
# to fill values we can also first define the set of values that we wanna set # 
values = {"A":40,"B":30}
df.fillna(value =values) # fillna works column wise , drop occurs row wise , selection occurs column wise

      A  B    C    D
0   1.0  2  1.0  1.0
1   2.0  2  2.0  NaN
2  40.0  3  3.0  NaN
3   4.0  4  NaN  NaN
4   5.0  5  NaN  5.0